package traceclient;

import listeners.HandMovementListener;
import listeners.MessageTransmitter;

/**
 *
 * @author James
 */
public class Tracer extends javax.swing.JFrame implements HandMovementListener, MessageTransmitter{
    double hx, hy, hz;
    TraceClient client;
    HandViewer viewer;

    /** Creates new form Tracer */
    public Tracer() {
        initComponents();        
        setLocation(750, 0);

        //init variables
        client = new TraceClient();
        client.addHandListener(this);
        client.start();
        
        //init subwindows
        viewer = new HandViewer(client);
        viewer.setLocation(getLocation().x, getLocation().y + getHeight());
        viewer.setVisible(true);
    }

    public void handMoved(double x, double y, double z) {
        hx = x;
        hy = y;
        hz = z;
    }

    public void newCalibration(double tx, double ty, double bx, double by, double z) { }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCalibrate = new javax.swing.JButton();
        lText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCalibrate.setText("Calibrate");
        bCalibrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalibrateActionPerformed(evt);
            }
        });

        lText.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bCalibrate, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lText, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCalibrate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCalibrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalibrateActionPerformed
        client.calibrate(this);
    }//GEN-LAST:event_bCalibrateActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tracer().setVisible(true);
            }
        });
    }

    public void println(String msg) {
        lText.setText(msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalibrate;
    private javax.swing.JLabel lText;
    // End of variables declaration//GEN-END:variables

}
